### PR TITLE
DMM2K分辨率的横版封面

### PR DESCRIPTION
**Pull request by anyingxiuluo**
#294
将dmm刮削的图片地址中pics.dmm.co.jp替换成awsimgsrc.dmm.co.jp/pics_dig，这样如果有高清图片会用高清图片，没有高清图片的走awsimgsrc.dmm.co.jp/pics_dig也能正常下载图片

### CODE REVIEW

**Comment by cgkings** [comment]
终于有一个结果更新火炬的大佬了，但是你的fork为啥不构建成exe呢

**Comment by cgkings** [comment]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\main_window\main_window.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\cut_window.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\scraper.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\crawler.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\crawlers\getchu_dmm.py", line 6, in <module>
ImportError: cannot import name 'dmm' from 'models.crawlers' (unknown location)

**Comment by anyingxiuluo** [comment]
> Traceback (most recent call last):
> File "main.py", line 13, in 
> File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> File "controllers\main_window\main_window.py", line 13, in 
> File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> File "controllers\cut_window.py", line 12, in 
> File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> File "models\core\scraper.py", line 15, in 
> File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> File "models\core\crawler.py", line 12, in 
> File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> File "models\crawlers\getchu_dmm.py", line 6, in 
> ImportError: cannot import name 'dmm' from 'models.crawlers' (unknown location)

你用源码运行，把src/models/crawlers/dmm.py这个文件替换成我库里的就行了，我这边测试没问题

**Comment by cgkings** [comment]
> > Traceback (most recent call last):
> > File "main.py", line 13, in
> > File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> > File "controllers\main_window\main_window.py", line 13, in
> > File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> > File "controllers\cut_window.py", line 12, in
> > File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> > File "models\core\scraper.py", line 15, in
> > File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> > File "models\core\crawler.py", line 12, in
> > File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> > File "models\crawlers\getchu_dmm.py", line 6, in
> > ImportError: cannot import name 'dmm' from 'models.crawlers' (unknown location)
> 
> 你用源码运行，把src/models/crawlers/dmm.py这个文件替换成我库里的就行了，我这边测试没问题

源码运行，需要把src/models/crawlers/dmm.py的最后增加一个pass才能运行，可能是你把if __name__ == "__main__":下面的代码全部都注释掉了的原因

**Pull request merged**
